[build]
  command = "npm install --save-dev terser && npm run build || npm run build:fallback"
  publish = "dist"

# Define environment variables
[build.environment]
  NODE_VERSION = "18"
  NPM_VERSION = "9"
  VITE_TERSER_INSTALLED = "true"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

[[headers]]
  for = "/*.mjs"
  [headers.values]
    Content-Type = "text/javascript"

[[headers]]
  for = "/*.js"
  [headers.values]
    Content-Type = "text/javascript"
